# config.yml

#city to create the streetnet, poi ...
city_name: "Dresden"

# for testing purposes
testing_phase: True
test_osm_street_package: 'output\test_network\osm_street_net_Dresden.gpkg'
test_osm_poi_package: 'output\test_network\osm_pois_Dresden.gpkg'

# input csv with necessary key value pairs
path_to_poi_csv: 'input\poi_key_value.CSV'

# osm-values for the key highway
street_types_list: ["primary", "secondary", "tertiary", "unclassified"]
