# config.yml

openweatherapi_key : 9f548b05df513f03b9295e7abff9f41a

#city to create the streetnet, poi ...
city_name: "Plauen"
country_code: "DE"
# 6 for cities

adminlevel_country : https://wiki.openstreetmap.org/wiki/DE:Grenze#Staatsgrenze_-_admin_level=2
adminlevel_for_cities : https://www.openstreetmap.org/ 

admin_level_country: 2
admin_level_city: 8

#info zu admin_level
# Leipzig = 6           check
# Halle (Saale) = 6     check
# Heidelberg = 6        check
# Leverkusen = 6        check
# Karlsruhe = 6         check
# Kiel = 6              check
# Chemnitz = 6          check
# Fürstenfeldbruck = 8  check
# Ratingen = 8          check
# Neumünster = 6         check
# Landau in der Pfalz = 6 check
# Gießen = 8            check
# München = 6           check
# Hamburg = 4           check

#if the city name has special character or so
english_city_name: False

#still download osm data even if data is in draftfolder
redownload : True


# for testing purposes only!
testing_phase: False
test_osm_street_package: 'output\test_network\osm_street_net_Dresden.gpkg'
test_osm_poi_package: 'output\test_network\osm_pois_Dresden.gpkg'

#if interim result wants to be safed, is not needed for internal computation
save_interim_results: true

# input csv with necessary key value pairs
path_to_poi_csv: 'src\data\input\poi_key_value.CSV'
path_to_area_csv: 'src\data\input\area_key_value.CSV'

#zensus
zensus_crs : "EPSG:3035"
zensus_url : "https://www.zensus2011.de/SharedDocs/Downloads/DE/Pressemitteilung/DemografischeGrunddaten/csv_Bevoelkerung_100m_Gitter.zip?__blob=publicationFile&v=2"

#gauskrueger crs
gauss_crs : EPSG:31468
# osm-values for the key highway
street_types_list: ["primary", "secondary", "tertiary", "unclassified", "residential"]
# visualisationparams
# not in code yet

#tessalation config
min_cluster_size : 50
number_of_polygons : 200
poi_categories : "all"

#street net buffersize in meter
street_buffer_size : 250

osm_points_kwargs:
  color: "blue"
  alpha: 0.5
  markersize: 5

outliers_kwargs:
  color: "red"
  alpha: 0.5
  markersize: 5
