# config.yml

street_types_list: ["primary", "secondary", "tertiary", "unclassified"]

city_name: "Dresden"

test_package: 'output\test_network\dresden_netz.gpkg'

safe_interim_results: True

path_to_poi_csv: 'input\poi_key_value.CSV'

pois_dictioanry:
  shop:
    - supermarket
    - grocery
    - clothes
    - boutique
    - electronics
    - computer
    - bakery
    - pharmacy
  amenity:
    - restaurant
    - hospital
    - school
    - park
    - place_of_worship
