# config.yml

#city to create the streetnet, poi ...
city_name: "Montreal"
country_code: "CA"

# for testing purposes
testing_phase: False
test_osm_street_package: 'output\test_network\osm_street_net_Dresden.gpkg'
test_osm_poi_package: 'output\test_network\osm_pois_Dresden.gpkg'

#if interim result wants to be safed, is not needed for internal compution
safe_interim_results: true

# input csv with necessary key value pairs
path_to_poi_csv: 'data\input\poi_key_value.CSV'
path_to_area_csv: 'data\input\area_key_value.CSV'

#zensus
zensus_crs : "EPSG:3035"
zensus_url : "https://www.zensus2011.de/SharedDocs/Downloads/DE/Pressemitteilung/DemografischeGrunddaten/csv_Bevoelkerung_100m_Gitter.zip?__blob=publicationFile&v=2"


# osm-values for the key highway
street_types_list: ["primary", "secondary", "tertiary", "unclassified", "residential"]
# visualisationparams
# not in code yet

osm_points_kwargs:
  color: "blue"
  alpha: 0.5
  markersize: 5

outliers_kwargs:
  color: "red"
  alpha: 0.5
  markersize: 5
