# config.yml

#city to create the streetnet, poi ...
city_name: "Zwickau"

# for testing purposes
testing_phase: True
test_osm_street_package: 'output\test_network\osm_street_net_Dresden.gpkg'
test_osm_poi_package: 'output\test_network\osm_pois_Dresden.gpkg'

safe_interim_results: true

# input csv with necessary key value pairs
path_to_poi_csv: 'data\input\poi_key_value.CSV'
path_to_area_csv: 'data\input\area_key_value.CSV'

# osm-values for the key highway
street_types_list: ["primary", "secondary", "tertiary", "unclassified"]
